
import { CourseOption } from '@/types/api';

export const coursesData: CourseOption[] = [
  { course_name: "Computer Science", course_taxonomy_id: 23989 },
  { course_name: "Data Science and Data Analytics", course_taxonomy_id: 67440 },
  { course_name: "Business Analytics", course_taxonomy_id: 24606 },
  { course_name: "Mechanical Engineering", course_taxonomy_id: 322 },
  { course_name: "Management Information Systems", course_taxonomy_id: 24496 },
  { course_name: "Electrical and Electronics Engineering", course_taxonomy_id: 609 },
  { course_name: "Electrical and Computer Engineering", course_taxonomy_id: 24586 },
  { course_name: "Computer and Information Systems", course_taxonomy_id: 24090 },
  { course_name: "Engineering Management Mem", course_taxonomy_id: 24241 },
  { course_name: "Industrial Engineering", course_taxonomy_id: 24462 },
  { course_name: "Civil Engineering", course_taxonomy_id: 268 },
  { course_name: "Computer Engineering", course_taxonomy_id: 24252 },
  { course_name: "Cybersecurity", course_taxonomy_id: 24021 },
  { course_name: "Information Technology", course_taxonomy_id: 269 },
  { course_name: "Mba", course_taxonomy_id: 24620 },
  { course_name: "Software Engineering", course_taxonomy_id: 24077 },
  { course_name: "Artificial Intelligence", course_taxonomy_id: 527 },
  { course_name: "Aerospace Engineering", course_taxonomy_id: 720 },
  { course_name: "Construction Management", course_taxonomy_id: 815 },
  { course_name: "Finance ", course_taxonomy_id: 24171 },
  { course_name: "Biotechnology", course_taxonomy_id: 189 },
  { course_name: "Business Administration and Management", course_taxonomy_id: 24582 },
  { course_name: "Human Computer Interaction", course_taxonomy_id: 24155 },
  { course_name: "Management Science", course_taxonomy_id: 23983 },
  { course_name: "Biomedical Engineering", course_taxonomy_id: 278 },
  { course_name: "Electrical Engineering", course_taxonomy_id: 357 },
  { course_name: "Robotics Technology", course_taxonomy_id: 662 },
  { course_name: "Public Health", course_taxonomy_id: 569 },
  { course_name: "Chemical Engineering", course_taxonomy_id: 23949 },
  { course_name: "Computer and Information Sciences General", course_taxonomy_id: 24278 },
  { course_name: "Logistics and Supply Chain Management", course_taxonomy_id: 24514 },
  { course_name: "Computational Science", course_taxonomy_id: 340 },
  { course_name: "Civil and Environmental Engineering", course_taxonomy_id: 541 },
  { course_name: "Automotive Engineering", course_taxonomy_id: 900 },
  { course_name: "Computer Networking and Telecommunications", course_taxonomy_id: 24275 },
  { course_name: "Information Science", course_taxonomy_id: 24334 },
  { course_name: "Health Information Technology", course_taxonomy_id: 640 },
  { course_name: "Technology Management and Entrepreneurship", course_taxonomy_id: 24405 },
  { course_name: "Mechatronics Robotics and Automation Engineering", course_taxonomy_id: 409 },
  { course_name: "Human Resources Management", course_taxonomy_id: 24302 },
  { course_name: "Materials Engineering", course_taxonomy_id: 683 },
  { course_name: "Project Management", course_taxonomy_id: 24575 },
  { course_name: "Architecture", course_taxonomy_id: 154 },
  { course_name: "Biomedical Informatics", course_taxonomy_id: 823 },
  { course_name: "Marketing ", course_taxonomy_id: 24327 },
  { course_name: "Biological Biosystems Engineering", course_taxonomy_id: 24110 },
  { course_name: "Chemical Petroleum", course_taxonomy_id: 24550 },
  { course_name: "Construction Engineering", course_taxonomy_id: 644 },
  { course_name: "Pharmacy", course_taxonomy_id: 310 },
  { course_name: "Accounting", course_taxonomy_id: 24565 },
  { course_name: "International Business Management", course_taxonomy_id: 24057 },
  { course_name: "Manufacturing Engineering", course_taxonomy_id: 24150 },
  { course_name: "Food Science", course_taxonomy_id: 353 },
  { course_name: "Systems Engineering", course_taxonomy_id: 24286 },
  { course_name: "Economics", course_taxonomy_id: 24609 },
  { course_name: "Information Studies", course_taxonomy_id: 749 },
  { course_name: "Pharmacology", course_taxonomy_id: 668 },
  { course_name: "Health Administration", course_taxonomy_id: 24374 },
  { course_name: "Engineering General", course_taxonomy_id: 24123 },
  { course_name: "Psychology", course_taxonomy_id: 253 },
  { course_name: "Pharmaceutical Sciences", course_taxonomy_id: 212 },
  { course_name: "Informatics", course_taxonomy_id: 24135 },
  { course_name: " Financial Management", course_taxonomy_id: 590 },
  { course_name: "Health Informatics and Management Systems", course_taxonomy_id: 392 },
  { course_name: "Financial Engineering", course_taxonomy_id: 24434 },
  { course_name: "International Business", course_taxonomy_id: 24232 },
  { course_name: "Aerospace and Mechanical Engineering", course_taxonomy_id: 923 },
  { course_name: "Environmental Science", course_taxonomy_id: 24403 },
  { course_name: "Business General", course_taxonomy_id: 24238 },
  { course_name: "Energy Systems Engineering", course_taxonomy_id: 24183 },
  { course_name: "Technology Innovation and Entrepreneurship", course_taxonomy_id: 23944 },
  { course_name: "Mathematics and Statistics", course_taxonomy_id: 544 },
  { course_name: "Embedded Systems", course_taxonomy_id: 885 },
  { course_name: "Environmental Mining", course_taxonomy_id: 24553 },
  { course_name: "Biomedical Sciences", course_taxonomy_id: 349 },
  { course_name: "Physics", course_taxonomy_id: 810 },
  { course_name: "Biology General", course_taxonomy_id: 232 },
  { course_name: "Econometrics and Quantitative Economics", course_taxonomy_id: 675 },
  { course_name: "Computational Mathematics", course_taxonomy_id: 805 },
  { course_name: "Chemistry", course_taxonomy_id: 470 },
  { course_name: "Telecommunications Engineering and Technology", course_taxonomy_id: 160 },
  { course_name: "Electrical Electronics and Communications Engineering", course_taxonomy_id: 570 },
  { course_name: "International Relations", course_taxonomy_id: 24188 },
  { course_name: "Computer Systems Engineering", course_taxonomy_id: 24600 },
  { course_name: "Structural Engineering", course_taxonomy_id: 901 },
  { course_name: "Product Design and Development", course_taxonomy_id: 24297 },
  { course_name: "Engineering Mechanics", course_taxonomy_id: 561 },
  { course_name: "Urban Studies", course_taxonomy_id: 744 },
  { course_name: "Modern Languages", course_taxonomy_id: 24554 },
  { course_name: "Executive Management Mba", course_taxonomy_id: 24618 },
  { course_name: "Drug Discovery and Regulatory Affairs", course_taxonomy_id: 267 },
  { course_name: "Environmental Management", course_taxonomy_id: 24064 },
  { course_name: "Organizational Leadership", course_taxonomy_id: 24066 },
  { course_name: "Urban Community and Regional Planning", course_taxonomy_id: 202 },
  { course_name: "Nursing", course_taxonomy_id: 446 },
  { course_name: "Education", course_taxonomy_id: 24162 },
  { course_name: "Sociology", course_taxonomy_id: 396 },
  { course_name: "Financial Mathematics", course_taxonomy_id: 913 },
  { course_name: "Transportation and Highway Engineering", course_taxonomy_id: 24127 },
  { course_name: "Law Enforcement Intelligence Analysis", course_taxonomy_id: 24521 },
  { course_name: "Medicine and Surgery(MBBS)", course_taxonomy_id: 41 },
  { course_name: "Mathematics", course_taxonomy_id: 430 },
  { course_name: "Computing Technology Mct", course_taxonomy_id: 24613 },
  { course_name: "Operations Research", course_taxonomy_id: 24249 },
  { course_name: "Engineering Design", course_taxonomy_id: 24276 },
  { course_name: "Operations Management", course_taxonomy_id: 23970 },
  { course_name: "Marine and Coastal Sciences", course_taxonomy_id: 24473 },
  { course_name: "Engineering Science", course_taxonomy_id: 481 },
  { course_name: "Toxicology", course_taxonomy_id: 867 },
  { course_name: "Nutrition Sciences", course_taxonomy_id: 813 },
  { course_name: "Health Care", course_taxonomy_id: 462 },
  { course_name: "Game and Interactive Media Design", course_taxonomy_id: 24267 },
  { course_name: "Neuroscience", course_taxonomy_id: 759 },
  { course_name: "Music", course_taxonomy_id: 329 },
  { course_name: "Cellular and Molecular Biology", course_taxonomy_id: 598 },
  { course_name: "Agricultural Engineering", course_taxonomy_id: 23969 },
  { course_name: "Analytics and Information Management", course_taxonomy_id: 118 },
  { course_name: "Sustainable Energy", course_taxonomy_id: 23960 },
  { course_name: "Biological Science", course_taxonomy_id: 767 },
  { course_name: "Design and Applied Arts", course_taxonomy_id: 525 },
  { course_name: "Landscape Architecture", course_taxonomy_id: 560 },
  { course_name: "Renewable Energy", course_taxonomy_id: 24201 },
  { course_name: "Electrical and Power Engineering", course_taxonomy_id: 187 },
  { course_name: "Library and Information Science", course_taxonomy_id: 872 },
  { course_name: "Intelligent Systems", course_taxonomy_id: 24325 },
  { course_name: "Communication General", course_taxonomy_id: 24407 },
  { course_name: "Law and Legal Studies", course_taxonomy_id: 24457 },
  { course_name: "Agriculture General", course_taxonomy_id: 24433 },
  { course_name: "Algorithms and Machine Learning", course_taxonomy_id: 444 },
  { course_name: "Materials Science ", course_taxonomy_id: 124 },
  { course_name: "Applied Economics", course_taxonomy_id: 24116 },
  { course_name: "Applied Mathematics", course_taxonomy_id: 459 },
  { course_name: "Modeling Virtual Environments and Simulation", course_taxonomy_id: 682 },
  { course_name: "Clinical Psychology", course_taxonomy_id: 53 },
  { course_name: "Counseling Psychology", course_taxonomy_id: 24595 },
  { course_name: "Business and Marketing Management", course_taxonomy_id: 24205 },
  { course_name: "Statistics", course_taxonomy_id: 320 },
  { course_name: "Microbiology", course_taxonomy_id: 529 },
  { course_name: "Dental Science", course_taxonomy_id: 783 },
  { course_name: "Public Administration", course_taxonomy_id: 24593 },
  { course_name: "Engineering and Industrial Management", course_taxonomy_id: 24388 },
  { course_name: "Digital Communications and Multimedia", course_taxonomy_id: 24313 },
  { course_name: "Kinesiology", course_taxonomy_id: 168 },
  { course_name: "Industrial and Organizational Psychology", course_taxonomy_id: 937 },
  { course_name: "Management and Business Analytics", course_taxonomy_id: 24049 },
  { course_name: "Human Factors and Ergonomics", course_taxonomy_id: 24129 },
  { course_name: "Organizational Behavior Studies", course_taxonomy_id: 23942 },
  { course_name: "Chemical and Biomolecular Engineering", course_taxonomy_id: 23966 },
  { course_name: "Architectural and Building Sciences Technology", course_taxonomy_id: 917 },
  { course_name: "Astronomy", course_taxonomy_id: 595 },
  { course_name: "Biochemistry and Molecular Biology", course_taxonomy_id: 735 },
  { course_name: "Health Sciences General", course_taxonomy_id: 230 },
  { course_name: "Taxation", course_taxonomy_id: 24058 },
  { course_name: "Finance and Investment", course_taxonomy_id: 23982 },
  { course_name: "Information Technology Project Management", course_taxonomy_id: 23994 },
  { course_name: "Petroleum Engineering", course_taxonomy_id: 24004 },
  { course_name: "Biochemistry", course_taxonomy_id: 263 },
  { course_name: "Sustainability Science", course_taxonomy_id: 171 },
  { course_name: "Chemical and Biological Engineering", course_taxonomy_id: 23993 },
  { course_name: "English", course_taxonomy_id: 24555 },
  { course_name: "Digital and Social Media Marketing", course_taxonomy_id: 24087 },
  { course_name: "Electronics Engineering", course_taxonomy_id: 231 },
  { course_name: "Drafting and Design Technology", course_taxonomy_id: 389 },
  { course_name: "Aviation Management", course_taxonomy_id: 24085 },
  { course_name: "Food Technology and Processing", course_taxonomy_id: 24091 },
  { course_name: "Data Analytics and Quantitative Analysis", course_taxonomy_id: 24099 },
  { course_name: "Public Policy Analysis", course_taxonomy_id: 23971 },
  { course_name: "Forensic Science", course_taxonomy_id: 582 },
  { course_name: "Technology and Innovation", course_taxonomy_id: 24492 },
  { course_name: "Interior Design", course_taxonomy_id: 94 },
  { course_name: "Actuarial Science", course_taxonomy_id: 24447 },
  { course_name: "Plant Sciences", course_taxonomy_id: 285 },
  { course_name: "Technical and Scientific Communication", course_taxonomy_id: 24394 },
  { course_name: "Graphic Design", course_taxonomy_id: 245 },
  { course_name: "Biostatistics", course_taxonomy_id: 756 },
  { course_name: "Hospitality Administration and Management", course_taxonomy_id: 24247 },
  { course_name: "Instructional Design", course_taxonomy_id: 259 },
  { course_name: "Communications Systems Technology", course_taxonomy_id: 239 },
  { course_name: "Design and Visual Communications", course_taxonomy_id: 604 },
  { course_name: "Astrophysics", course_taxonomy_id: 865 },
  { course_name: "Maritime Studies", course_taxonomy_id: 853 },
  { course_name: "Ocean Engineering", course_taxonomy_id: 23954 },
  { course_name: "Pharmacology and Toxicology", course_taxonomy_id: 95 },
  { course_name: "Exercise Science", course_taxonomy_id: 431 },
  { course_name: "Nanotechnology", course_taxonomy_id: 24397 },
  { course_name: "Sports Business and Management", course_taxonomy_id: 24319 },
  { course_name: "Political Science", course_taxonomy_id: 134 },
  { course_name: "Process Engineering", course_taxonomy_id: 23976 },
  { course_name: "Reading and Writing General", course_taxonomy_id: 473 },
  { course_name: "Fashion Design", course_taxonomy_id: 835 },
  { course_name: "Arts General", course_taxonomy_id: 378 },
  { course_name: "Epidemiology", course_taxonomy_id: 148 },
  { course_name: "Security Studies", course_taxonomy_id: 452 },
  { course_name: "Systems and Control", course_taxonomy_id: 24384 },
  { course_name: "International Studies", course_taxonomy_id: 24431 },
  { course_name: "Polymer Chemistry", course_taxonomy_id: 434 },
  { course_name: "Bachelor of Business Administration", course_taxonomy_id: 24030 },
  { course_name: "Integrated Circuit Design", course_taxonomy_id: 695 },
  { course_name: "New Media Art", course_taxonomy_id: 807 },
  { course_name: "International and Intercultural Communication", course_taxonomy_id: 24611 },
  { course_name: "Music Performance", course_taxonomy_id: 461 },
  { course_name: "Agronomy and Crop Science", course_taxonomy_id: 24284 },
  { course_name: "Social Work", course_taxonomy_id: 750 },
  { course_name: "Environmental Engineering", course_taxonomy_id: 24244 },
  { course_name: "Geomatics and Geographic Information Systems", course_taxonomy_id: 126 },
  { course_name: "Criminal Justice", course_taxonomy_id: 24141 },
  { course_name: "Research Methodology and Quantitative Methods", course_taxonomy_id: 398 },
  { course_name: "Adult Development and Aging", course_taxonomy_id: 447 },
  { course_name: "Computational Biology", course_taxonomy_id: 24013 },
  { course_name: "Fine and Studio Art", course_taxonomy_id: 208 },
  { course_name: "Mathematics and Computing", course_taxonomy_id: 24398 },
  { course_name: "Accountancy", course_taxonomy_id: 24157 },
  { course_name: "Radio and Television Broadcasting Technology", course_taxonomy_id: 24185 },
  { course_name: "Media and Communication", course_taxonomy_id: 348 },
  { course_name: "Public Relations", course_taxonomy_id: 24548 },
  { course_name: "Animal Sciences", course_taxonomy_id: 927 },
  { course_name: "Quality Management Systems", course_taxonomy_id: 24369 },
  { course_name: "Science Technology and Society", course_taxonomy_id: 163 },
  { course_name: "History", course_taxonomy_id: 24023 },
  { course_name: "Media Studies", course_taxonomy_id: 615 },
  { course_name: "Human Resources Development", course_taxonomy_id: 24081 },
  { course_name: "Computer Graphics", course_taxonomy_id: 24078 },
  { course_name: "Web Development", course_taxonomy_id: 24512 },
  { course_name: "Game Design and Development", course_taxonomy_id: 24420 },
  { course_name: "Broadcast Journalism", course_taxonomy_id: 388 },
  { course_name: "Biochemical Engineering", course_taxonomy_id: 23975 },
  { course_name: "Global Studies", course_taxonomy_id: 24537 },
  { course_name: "Journalism", course_taxonomy_id: 441 },
  { course_name: "Physician Assistance", course_taxonomy_id: 362 },
  { course_name: "International Law", course_taxonomy_id: 24422 },
  { course_name: "Aeronautical Engineering", course_taxonomy_id: 856 },
  { course_name: "Mental Health Counseling", course_taxonomy_id: 23963 },
  { course_name: "Genetics", course_taxonomy_id: 732 },
  { course_name: "Foods Nutrition and Wellness Studies", course_taxonomy_id: 567 },
  { course_name: "Applied Psychology", course_taxonomy_id: 576 },
  { course_name: "Film Studies", course_taxonomy_id: 500 },
  { course_name: "Animal and Veterinary Science", course_taxonomy_id: 571 },
  { course_name: "Criminology and Criminal Justice", course_taxonomy_id: 24073 },
  { course_name: "Architectural Engineering", course_taxonomy_id: 665 },
  { course_name: "Engineering and Technology", course_taxonomy_id: 24270 },
  { course_name: "Financial Economics", course_taxonomy_id: 24220 },
  { course_name: "Mathematics and Computer Science", course_taxonomy_id: 688 },
  { course_name: "Early Childhood Education", course_taxonomy_id: 24455 },
  { course_name: "Network and System Administration", course_taxonomy_id: 24137 },
  { course_name: "Ecology", course_taxonomy_id: 342 },
  { course_name: "Microbiology and Immunology", course_taxonomy_id: 873 },
  { course_name: "Environmental Studies", course_taxonomy_id: 24428 },
  { course_name: "Business Communication", course_taxonomy_id: 24393 },
  { course_name: "Orthotics and Prosthetics", course_taxonomy_id: 456 },
  { course_name: "English Language and Literature", course_taxonomy_id: 24477 },
  { course_name: "Environmental Health", course_taxonomy_id: 155 },
  { course_name: "Human Development and Family Studies", course_taxonomy_id: 75 },
  { course_name: "Nuclear Engineering Technology", course_taxonomy_id: 24083 },
  { course_name: "Tourism and Travel Management", course_taxonomy_id: 24592 },
  { course_name: "Analytics and Modeling", course_taxonomy_id: 943 },
  { course_name: "Agribusiness Operations", course_taxonomy_id: 24549 },
  { course_name: "Animation and Special Effects", course_taxonomy_id: 377 },
  { course_name: "Multi Interdisciplinary Studies General", course_taxonomy_id: 24362 },
  { course_name: "Creative Arts and Practice", course_taxonomy_id: 517 },
  { course_name: "Human Services", course_taxonomy_id: 24260 },
  { course_name: "Medical Physics", course_taxonomy_id: 722 },
  { course_name: "Law and Business", course_taxonomy_id: 24311 },
  { course_name: "Theater Arts", course_taxonomy_id: 941 },
  { course_name: "Sports Science", course_taxonomy_id: 147 },
  { course_name: "Water Resources Engineering", course_taxonomy_id: 24478 },
  { course_name: "Molecular Biology", course_taxonomy_id: 374 },
  { course_name: "Business and Managerial Economics", course_taxonomy_id: 24546 },
  { course_name: "Real Estate", course_taxonomy_id: 817 },
  { course_name: "Industrial Design and Technology", course_taxonomy_id: 23945 },
  { course_name: "Engineering Physics", course_taxonomy_id: 934 },
  { course_name: "Polymer and Plastics Engineering", course_taxonomy_id: 663 },
  { course_name: "Medicinal and Pharmaceutical Chemistry", course_taxonomy_id: 631 },
  { course_name: "Agricultural and Food Products Processing", course_taxonomy_id: 23939 },
  { course_name: "Immunology", course_taxonomy_id: 381 },
  { course_name: "Peace and Conflict Resolution Studies", course_taxonomy_id: 47 },
  { course_name: "Anthropology", course_taxonomy_id: 32 },
  { course_name: "Mining and Mineral Engineering", course_taxonomy_id: 24470 },
  { course_name: "Sales and Marketing Education", course_taxonomy_id: 24435 },
  { course_name: "Strategic Management", course_taxonomy_id: 24450 },
  { course_name: "Agricultural Economics", course_taxonomy_id: 24364 },
  { course_name: "Occupational Safety and Health Technology", course_taxonomy_id: 24102 },
  { course_name: "Clinical Regulatory Affairs", course_taxonomy_id: 549 },
  { course_name: "Conducting", course_taxonomy_id: 24499 },
  { course_name: "Medical Informatics", course_taxonomy_id: 88 },
  { course_name: "Social Sciences", course_taxonomy_id: 883 },
  { course_name: "Horticultural Science", course_taxonomy_id: 755 },
  { course_name: "Exercise Physiology", course_taxonomy_id: 141 },
  { course_name: "Earth Science", course_taxonomy_id: 438 },
  { course_name: "Building Construction Technology", course_taxonomy_id: 757 },
  { course_name: "Geography", course_taxonomy_id: 166 },
  { course_name: "Linguistics", course_taxonomy_id: 24138 },
  { course_name: "Applied Physics", course_taxonomy_id: 271 },
  { course_name: "Transportation Management", course_taxonomy_id: 24142 },
  { course_name: "International Health", course_taxonomy_id: 279 },
  { course_name: "Interior Architecture", course_taxonomy_id: 393 },
  { course_name: "Business Computing", course_taxonomy_id: 24513 },
  { course_name: "Laser and Optical Engineering", course_taxonomy_id: 252 },
  { course_name: "Communication Sciences and Disorders", course_taxonomy_id: 280 },
  { course_name: "Social Justice and Human Rights", course_taxonomy_id: 24536 },
  { course_name: "Advertising", course_taxonomy_id: 24309 },
  { course_name: "Physical Therapy", course_taxonomy_id: 491 },
  { course_name: "Creative Writing", course_taxonomy_id: 24005 },
  { course_name: "Geological Engineering", course_taxonomy_id: 24214 },
  { course_name: "Real Estate Development", course_taxonomy_id: 24530 },
  { course_name: "Space Systems Operations", course_taxonomy_id: 24182 },
  { course_name: "Environmental Engineering Technology", course_taxonomy_id: 24181 },
  { course_name: "Innovation Leadership Engineering Entrepreneurship", course_taxonomy_id: 24160 },
  { course_name: "Development Economics and International Development", course_taxonomy_id: 24037 },
  { course_name: "Machine Tool Technology", course_taxonomy_id: 24175 },
  { course_name: "Geosciences", course_taxonomy_id: 215 },
  { course_name: "Enterprise Risk Management", course_taxonomy_id: 24377 },
  { course_name: "Philosophy", course_taxonomy_id: 523 },
  { course_name: "Digital Image Processing", course_taxonomy_id: 737 },
  { course_name: "Counselor Education", course_taxonomy_id: 24165 },
  { course_name: "Optics", course_taxonomy_id: 790 },
  { course_name: "Criminology", course_taxonomy_id: 418 },
  { course_name: "Archaeology", course_taxonomy_id: 942 },
  { course_name: "Molecular Medicine", course_taxonomy_id: 448 },
  { course_name: "Paper Science and Engineering", course_taxonomy_id: 210 },
  { course_name: "Health Management and Clinical Assistance", course_taxonomy_id: 24413 },
  { course_name: "Automotive Technology", course_taxonomy_id: 612 },
  { course_name: "Signal Geospatial Intelligence", course_taxonomy_id: 206 },
  { course_name: "Cognitive Science", course_taxonomy_id: 24253 },
  { course_name: "Entomology", course_taxonomy_id: 591 },
  { course_name: "Quantum Technologies", course_taxonomy_id: 904 },
  { course_name: "Geology", course_taxonomy_id: 660 },
  { course_name: "Recording Arts Technology", course_taxonomy_id: 890 },
  { course_name: "Welding Engineering Technology", course_taxonomy_id: 443 },
  { course_name: "Clinical Nurse Leader", course_taxonomy_id: 287 },
  { course_name: "Computer Forensics", course_taxonomy_id: 24213 },
  { course_name: "Complementary Integrative Healthcare", course_taxonomy_id: 397 },
  { course_name: "Water Wetlands and Marine Resources Management", course_taxonomy_id: 700 },
  { course_name: "Environmental Education", course_taxonomy_id: 24616 },
  { course_name: "Packaging Science", course_taxonomy_id: 874 },
  { course_name: "Human Sciences", course_taxonomy_id: 855 },
  { course_name: "Teacher Education Multiple Levels", course_taxonomy_id: 24056 },
  { course_name: "Marketing Research", course_taxonomy_id: 24524 },
  { course_name: "Mass Communications", course_taxonomy_id: 364 },
  { course_name: "Intellectual Property", course_taxonomy_id: 24231 },
  { course_name: "Metallurgical Engineering", course_taxonomy_id: 312 },
  { course_name: "Visual and Performing Arts General", course_taxonomy_id: 115 },
  { course_name: "Ecommerce", course_taxonomy_id: 24541 }
];
