// Define types for the CollegeFinder form
export interface FormData {
  degree?: 'Bachelor\'s' | 'Master\'s';
  country: string;
  major: string;
  intendedCourseTaxonomyId: string; // Added this field
  undergradCollege: string;
  undergradMajor: string;
  score: number;
  scoreType: string;
  backlogs: number;
  englishTest: string | null;
  englishScore: number;
  aptitudeTest: string;
  workExperience: number;
  researchPapers: string;
  projects: number;
  gmatScore?: number;
  greVerbal?: number;
  greQuants?: number;
  greAwa?: number;
}

export interface University {
  name: string;
  country: string;
  rank: number;
  logo: string;
  matchPercentage: number;
  programs: string[];
  university_courses_id?: string;
  university_courses_credential?: string;
  university_courses_name?: string;
  university_courses_tuition_usd?: number;
  university_courses_level?: number;
  location_name?: string;
  university_courses_slug?: string;
  university_abb?: string;
  is_partner?: boolean;
  university_courses_is_partner?: boolean;
  university_courses_tuition_local?: number;
  university_courses_duration?: number;
  university_id?: string;
  university_slug?: string;
  annual_fee?: number;
}

// Country data with flags
export const countries: Country[] = [
  { name: "United States", flag: "🇺🇸", code: "US" },
  { name: "United Kingdom", flag: "🇬🇧", code: "UK" },
  { name: "Australia & New Zealand", flag: "🇦🇺", code: "AU" },
  { name: "Canada", flag: "🇨🇦", code: "CA" },
  { name: "European Union", flag: "🇪🇺", code: "EU" },
];

// List of majors/courses for study
export const majors: string[] = [
  "Computer Science",
  "Data Science and Data Analytics",
  "Business Analytics",
  "Mechanical Engineering",
  "Management Information Systems",
  "Electrical and Electronics Engineering",
  "Electrical and Computer Engineering",
  "Computer and Information Systems",
  "Engineering Management Mem",
  "Industrial Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Cybersecurity",
  "Information Technology",
  "Mba",
  "Software Engineering",
  "Artificial Intelligence",
  "Aerospace Engineering",
  "Construction Management",
  "Finance",
  "Biotechnology",
  "Business Administration and Management",
  "Human Computer Interaction",
  "Management Science",
  "Biomedical Engineering",
  "Electrical Engineering",
  "Robotics Technology",
  "Public Health",
  "Chemical Engineering",
  "Computer and Information Sciences General",
  "Logistics and Supply Chain Management",
  "Computational Science",
  "Civil and Environmental Engineering",
  "Automotive Engineering",
  "Computer Networking and Telecommunications",
  "Information Science",
  "Health Information Technology",
  "Technology Management and Entrepreneurship",
  "Mechatronics Robotics and Automation Engineering",
  "Human Resources Management",
  "Materials Engineering",
  "Project Management",
  "Architecture",
  "Biomedical Informatics",
  "Marketing",
  "Biological Biosystems Engineering",
  "Chemical Petroleum",
  "Construction Engineering",
  "Pharmacy",
  "Accounting",
  "International Business Management",
  "Manufacturing Engineering",
  "Food Science",
  "Systems Engineering",
  "Economics",
  "Information Studies",
  "Pharmacology",
  "Health Administration",
  "Engineering General",
  "Psychology",
  "Pharmaceutical Sciences",
  "Informatics",
  "Financial Management",
  "Health Informatics and Management Systems",
  "Financial Engineering",
  "International Business",
  "Aerospace and Mechanical Engineering",
  "Environmental Science",
  "Business General",
  "Energy Systems Engineering",
  "Technology Innovation and Entrepreneurship",
  "Mathematics and Statistics",
  "Embedded Systems",
  "Environmental Mining",
  "Biomedical Sciences",
  "Physics",
  "Biology General",
  "Econometrics and Quantitative Economics",
  "Computational Mathematics",
  "Chemistry",
  "Telecommunications Engineering and Technology",
  "Electrical Electronics and Communications Engineering",
  "International Relations",
  "Computer Systems Engineering",
  "Structural Engineering",
  "Product Design and Development",
  "Engineering Mechanics",
  "Urban Studies",
  "Modern Languages",
  "Executive Management Mba",
  "Drug Discovery and Regulatory Affairs",
  "Environmental Management",
  "Organizational Leadership",
  "Urban Community and Regional Planning",
  "Nursing",
  "Education",
  "Sociology",
  "Financial Mathematics",
  "Transportation and Highway Engineering",
  "Law Enforcement Intelligence Analysis",
  "Medicine and Surgery(MBBS)",
  "Mathematics",
  "Computing Technology Mct",
  "Operations Research",
  "Engineering Design",
  "Operations Management",
  "Marine and Coastal Sciences",
  "Engineering Science",
  "Toxicology",
  "Nutrition Sciences",
  "Health Care",
  "Game and Interactive Media Design",
  "Neuroscience",
  "Music",
  "Cellular and Molecular Biology",
  "Agricultural Engineering",
  "Analytics and Information Management",
  "Sustainable Energy",
  "Biological Science",
  "Design and Applied Arts",
  "Landscape Architecture",
  "Renewable Energy",
  "Electrical and Power Engineering",
  "Library and Information Science",
  "Intelligent Systems",
  "Law and Legal Studies",
  "Agriculture General",
  "Communication General",
  "Algorithms and Machine Learning",
  "Materials Science",
  "Applied Economics",
  "Applied Mathematics",
  "Modeling Virtual Environments and Simulation",
  "Clinical Psychology",
  "Counseling Psychology",
  "Business and Marketing Management",
  "Statistics",
  "Microbiology",
  "Dental Science",
  "Public Administration",
  "Engineering and Industrial Management",
  "Digital Communications and Multimedia",
  "Kinesiology",
  "Industrial and Organizational Psychology",
  "Management and Business Analytics",
  "Human Factors and Ergonomics",
  "Organizational Behavior Studies",
  "Chemical and Biomolecular Engineering",
  "Architectural and Building Sciences Technology",
  "Astronomy",
  "Biochemistry and Molecular Biology",
  "Health Sciences General",
  "Taxation",
  "Finance and Investment",
  "Information Technology Project Management",
  "Petroleum Engineering",
  "Biochemistry",
  "Sustainability Science",
  "Chemical and Biological Engineering",
  "English",
  "Digital and Social Media Marketing",
  "Electronics Engineering",
  "Drafting and Design Technology",
  "Aviation Management",
  "Food Technology and Processing",
  "Data Analytics and Quantitative Analysis",
  "Public Policy Analysis",
  "Forensic Science",
  "Technology and Innovation",
  "Interior Design",
  "Actuarial Science",
  "Plant Sciences",
  "Technical and Scientific Communication",
  "Graphic Design",
  "Biostatistics",
  "Hospitality Administration and Management",
  "Instructional Design",
  "Communications Systems Technology",
  "Design and Visual Communications",
  "Astrophysics",
  "Maritime Studies",
  "Ocean Engineering",
  "Pharmacology and Toxicology",
  "Exercise Science",
  "Nanotechnology",
  "Sports Business and Management",
  "Political Science",
  "Process Engineering",
  "Reading and Writing General",
  "Fashion Design",
  "Arts General",
  "Epidemiology",
  "Security Studies",
  "Systems and Control",
  "International Studies",
  "Polymer Chemistry",
  "Bachelor of Business Administration",
  "Integrated Circuit Design",
  "New Media Art",
  "International and Intercultural Communication",
  "Music Performance",
  "Agronomy and Crop Science",
  "Social Work",
  "Environmental Engineering",
  "Geomatics and Geographic Information Systems",
  "Criminal Justice",
  "Research Methodology and Quantitative Methods",
  "Adult Development and Aging",
  "Computational Biology",
  "Fine and Studio Art",
  "Mathematics and Computing",
  "Accountancy",
  "Radio and Television Broadcasting Technology",
  "Media and Communication",
  "Public Relations",
  "Animal Sciences",
  "Quality Management Systems",
  "Science Technology and Society",
  "History",
  "Media Studies",
  "Human Resources Development",
  "Computer Graphics",
  "Web Development",
  "Game Design and Development",
  "Broadcast Journalism",
  "Biochemical Engineering",
  "Global Studies",
  "Journalism",
  "International Law",
  "Physician Assistance",
  "Aeronautical Engineering",
  "Mental Health Counseling",
  "Genetics",
  "Foods Nutrition and Wellness Studies",
  "Applied Psychology",
  "Film Studies",
  "Animal and Veterinary Science",
  "Criminology and Criminal Justice",
  "Architectural Engineering",
  "Engineering and Technology",
  "Financial Economics",
  "Mathematics and Computer Science",
  "Early Childhood Education",
  "Network and System Administration",
  "Ecology",
  "Microbiology and Immunology",
  "Environmental Studies",
  "Business Communication",
  "Orthotics and Prosthetics",
  "English Language and Literature",
  "Environmental Health",
  "Human Development and Family Studies",
  "Nuclear Engineering Technology",
  "Tourism and Travel Management",
  "Analytics and Modeling",
  "Agribusiness Operations",
  "Animation and Special Effects",
  "Multi Interdisciplinary Studies General",
  "Creative Arts and Practice",
  "Human Services",
  "Medical Physics",
  "Law and Business",
  "Theater Arts",
  "Sports Science",
  "Water Resources Engineering",
  "Molecular Biology",
  "Business and Managerial Economics",
  "Real Estate",
  "Industrial Design and Technology",
  "Engineering Physics",
  "Polymer and Plastics Engineering",
  "Medicinal and Pharmaceutical Chemistry",
  "Agricultural and Food Products Processing",
  "Immunology",
  "Peace and Conflict Resolution Studies",
  "Anthropology",
  "Mining and Mineral Engineering",
  "Sales and Marketing Education",
  "Strategic Management",
  "Agricultural Economics",
  "Occupational Safety and Health Technology",
  "Clinical Regulatory Affairs",
  "Conducting",
  "Medical Informatics",
  "Social Sciences",
  "Horticultural Science",
  "Exercise Physiology",
  "Earth Science",
  "Building Construction Technology",
  "Geography",
  "Linguistics",
  "Applied Physics",
  "Transportation Management",
  "International Health",
  "Interior Architecture",
  "Business Computing",
  "Laser and Optical Engineering",
  "Communication Sciences and Disorders",
  "Social Justice and Human Rights",
  "Advertising",
  "Physical Therapy",
  "Creative Writing",
  "Geological Engineering",
  "Real Estate Development",
  "Space Systems Operations",
  "Environmental Engineering Technology",
  "Innovation Leadership Engineering Entrepreneurship",
  "Development Economics and International Development",
  "Machine Tool Technology",
  "Geosciences",
  "Enterprise Risk Management",
  "Philosophy",
  "Digital Image Processing",
  "Counselor Education",
  "Optics",
  "Criminology",
  "Archaeology",
  "Molecular Medicine",
  "Paper Science and Engineering",
  "Health Management and Clinical Assistance",
  "Automotive Technology",
  "Signal Geospatial Intelligence",
  "Cognitive Science",
  "Entomology",
  "Quantum Technologies",
  "Geology",
  "Recording Arts Technology",
  "Welding Engineering Technology",
  "Clinical Nurse Leader",
  "Computer Forensics",
  "Complementary Integrative Healthcare",
  "Water Wetlands and Marine Resources Management",
  "Environmental Education",
  "Packaging Science",
  "Human Sciences",
  "Teacher Education Multiple Levels",
  "Marketing Research",
  "Mass Communications",
  "Intellectual Property",
  "Metallurgical Engineering",
  "Visual and Performing Arts General",
  "Ecommerce",
  "Food Preparation",
  "Civil and Construction Engineering",
  "Public Health Education",
  "Arts and Entertainment Management",
  "Higher Education Administration",
  "Occupational Therapy",
  "Family Practice Nurse Practitioner",
  "Multimedia",
  "Applied Behavior Analysis",
  "Urban Education and Leadership",
  "Religious Studies",
  "Biomedical Technology",
  "Sustainable Business",
  "Cell Biology and Anatomy",
  "Professional Studies",
  "Molecular Biochemistry",
  "Photography",
  "Water Quality and Wastewater Treatment",
  "Development Studies",
  "Industrial Safety Technology",
  "Digital Arts",
  "Telecommunications Systems and Networks",
  "Urban Development Planning",
  "Language Literature and Cultural Studies",
  "Music Technology",
  "Biochemistry Biophysics and Molecular Biology",
  "Liberal Arts and Sciences",
  "Branding Integrated Communications Bic",
  "Dance",
  "Plant Pathology",
  "Educational Instructional and Curriculum Supervision",
  "Speech Language Pathology and Audiology",
  "Community Development",
  "Educational Administration",
  "Genetic Counseling",
  "Genomics",
  "Medical Organizations and Systems",
  "Digital Creative Media",
  "Health Policy Analysis",
  "Urban Planning and Public Administration",
  "Educational Technology",
  "Gerontology",
  "Child and Adolescent Studies",
  "Aquaculture",
  "Solar Energy Technology",
  "Game Programming",
  "Nursing Practice",
  "Global Sustainable Development",
  "Mathematics Teacher Education",
  "Geotechnical and Geo Environmental Engineering",
  "Applied Biological Sciences",
  "Emergency Management Homeland Security",
  "Educational Psychology",
  "Clinical Laboratory Science",
  "Special Education",
  "Health and Physical Fitness",
  "Marine Biology",
  "Accounting and Analytics",
  "Telecommunications Management",
  "Community Health and Preventive Medicine",
  "Natural Resources Management and Policy",
  "Humanities",
  "Art History Criticism and Conservation",
  "Soil Science",
  "Innovation Engineering",
  "Zoology",
  "Hydrology and Water Resources Science",
  "Nursing Administration",
  "School Counseling",
  "Physiology",
  "Atmospheric Sciences and Meteorology",
  "American Studies",
  "Nursing Education",
  "Engineering Material",
  "Family and Consumer Sciences",
  "International Policy Analysis",
  "Textile Sciences and Engineering",
  "Sustainability Studies",
  "Women S Studies",
  "Communications Technologies",
  "Physical Education Teaching and Coaching",
  "Comparative Literature",
  "International Economics",
  "Land Use Planning",
  "Plant Molecular Biology",
  "Sports Studies",
  "Neurobiology and Behavior",
  "Sports and Fitness Administration",
  "Rehabilitation Science",
  "Fire Science",
  "Environmental Policy and Management",
  "Teaching English As A Second Language Esl",
  "Games and Entertainment Design",
  "Architectural History and Criticism",
  "Ecology and Evolutionary Biology",
  "Chemical and Physical Oceanography",
  "Molecular Pharmacology",
  "Science Technology",
  "Anatomy",
  "School Psychology",
  "Air and Space Operations Technology",
  "Technology Leadership and Management",
  "Athletic Training",
  "Chemical Education",
  "Political Economy",
  "Music Theory and Composition",
  "Mechanical Engineering Technology",
  "Health Promotion",
  "Developmental Psychology",
  "Adult and Technical Education",
  "Surgical Nursing",
  "College Student Counseling and Personnel Services",
  "Illustration",
  "Nonprofit and Non Governmental Organizations",
  "Cultural Resource Management",
  "Health Technology",
  "Planetary Astronomy and Science",
  "Architectural Technology",
  "Elementary School Teaching",
  "Biofabrication and Biomaterials",
  "Product Innovation and Computing",
  "Dramatics",
  "Agriculture Education Services",
  "Studio Arts",
  "Applied Linguistics",
  "Computer Science Mathematical Sciences",
  "Technology and International Affairs",
  "Mental Health Nursing",
  "Forestry",
  "Atmospheric Chemistry and Climatology",
  "Arts Management and Arts Entrepreneurship",
  "Biophysics",
  "Speech Language Pathology",
  "Advertising Public Relations and Media Design",
  "Computational and Medicinal Chemistry",
  "Education Administration and Supervision",
  "Marriage and Family Therapy",
  "Leadership and Administration",
  "Botany",
  "Playwriting and Screenwriting",
  "Curriculum and Instruction",
  "Facilities Planning and Management",
  "Medical Imaging Technology",
  "Graphics Visualization and Computational Fabrication",
  "Natural Sciences",
  "Biosciences",
  "Meteorology",
  "Applied Life Science",
  "Graphic Communications",
  "Psychological Method",
  "Governance Policy and Administration",
  "Environmental Toxicology",
  "Purchasing Procurement and Contracts Management",
  "Environmental System",
  "Behavioral Sciences",
  "Learning Sciences",
  "Telecommunications Technology",
  "Wildlife Fish and Wildlands Science and Management",
  "Biological Science Education",
  "Directing and Theatrical Production",
  "Asian Studies",
  "Fiber Textile and Weaving Arts",
  "Natural Resource Recreation and Tourism",
  "Speech and Hearing Sciences",
  "Natural Resources and Conservation",
  "Vocational Rehabilitation Counseling",
  "German",
  "Fishing and Fisheries",
  "Organizational Communication",
  "Organization Development",
  "Pharmaceutical Marketing",
  "Language Interpretation and Translation",
  "Coaching and Talent Development",
  "European Studies",
  "Merchandising and Buying Operations",
  "Ceramic Sciences and Engineering",
  "Earth Systems Environmental Science Technology",
  "Restaurant and Food Services Management",
  "Systematic Biology",
  "Bioethics and Medical Ethics",
  "Diplomacy and Trade",
  "Forest Sciences and Biology",
  "Art Education",
  "Pediatric Nursing",
  "Musical Theater",
  "Clinical Child Psychology",
  "Graphic Communication Design",
  "Wildlife Biology",
  "Spanish",
  "Retailing",
  "Forensic Chemistry",
  "Accounting and Taxation",
  "Geophysics and Seismology",
  "Experimental Psychology",
  "Crop Production",
  "Cellular Biology and Histology",
  "Human Development Family Studies and Child Care",
  "Wind Energy",
  "Radiology",
  "General Literature",
  "Musicology and Ethnomusicology",
  "Adult and Continuing Education",
  "Intelligence General",
  "Parks Recreation and Leisure Facilities Management",
  "English Literature With Film Studies",
  "Clinical and Experimental Therapeutics",
  "Pastoral Counseling",
  "Accountacy and Finance",
  "Range Science",
  "Biodiversity",
  "Conservation Biology",
  "Politics and Contemporary History",
  "Public Health Nursing",
  "Emergency Care Attendance",
  "Advanced Manufacturing and Quality Control Technologies Focused On Composition Properties and Integrity of Materials",
  "Education Policy",
  "Polymer Engineering",
  "Nuclear Engineering",
  "Latin American Studies",
  "Christian Studies",
  "Applied and Industrial Mathematic",
  "Near and Middle Eastern Studies",
  "Metal and Jewelry Arts",
  "Museum Studies",
  "Intercultural Multicultural and Diversity Studies",
  "American Indian Studies",
  "Educational Evaluation and Research",
  "Music Teacher Education",
  "Viticulture and Enology",
  "Clinical Pastoral Counseling",
  "Social Studies Teacher Education",
  "Child Development",
  "Devised Theatre and Performance and Advanced Devising Practice",
  "High School Teaching",
  "Crime and Investigative Studies",
  "Community Health Services",
  "Environmental Control Technologies",
  "Sales and Distribution",
  "Vocational Technical Education",
  "Public Services",
  "French",
  "Administration of Elementary and Secondary Education",
  "Secondary Education Teacher Leader Ma",
  "Race and Ethnicity",
  "Poultry Science",
  "Regional Studies",
  "Ceramics",
  "Chinese Medicine and Herbology",
  "Japanese",
  "Community Psychology",
  "Addiction Counseling",
  "Middle School Teaching",
  "Ethnic Studies General",
  "Reading Teacher Education",
  "Communication and Rhetoric",
  "Teaching and Learning Secondary",
  "Rhetoric and Composition",
  "Biometrics",
  "Operational Oceanography",
  "International and Comparative Education",
  "Merchant Marine Science",
  "Youth Services",
  "Education of Individuals In Secondary Special Education Programs",
  "Family and Community Services",
  "Professional Communication Concentration",
  "Explosive Ordnance Bomb Disposal",
  "Public History",
  "Educational Technology Leadership",
  "Literacy Studies",
  "Writing General",
  "Science Teacher Education",
  "Molecular Physiology",
  "Early Childhood Special Education",
  "Fire Protection",
  "Foreign Languages and Literatures General",
  "Classics",
  "Philosophy and Religious Studies General",
  "Multilingualism and Education",
  "French Studies",
  "History and Philosophy of Science and Technology",
  "African Studies",
  "Teaching and Learning Primary",
  "Refugee and Forced Migration Studies",
  "Music Pedagogy",
  "Information Psychological Warfare and Military Media Relations",
  "Elementary Studies K",
  "Educational Technology Studies",
  "Medical Illustrating",
  "Languages and Linguistic",
  "Music Therapy",
  "Ecology Evolution and Related Sciences",
  "Animal Nutrition",
  "Native American Languages",
  "High School Administration",
  "Southeast Asian Studies",
  "Multicultural Education",
  "Holocaust and Related Studies",
  "East Asian Studies",
  "Clinical Nurse Specialist",
  "Spanish Teacher Education",
  "Archival Studies",
  "French Teacher Education",
  "Chinese",
  "Conservation Science",
  "Pharmaceutical Marketing and Management",
  "War and Conflict Studies",
  "Jazz Studies",
  "Portuguese",
  "Italian",
  "Russian",
  "Language Arts Education"
];

// Mock universities for demonstration
export const mockUniversities: University[] = [
  {
    name: "Massachusetts Institute of Technology",
    country: "United States",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/MIT_logo.svg/1200px-MIT_logo.svg.png",
    rank: 1,
    matchPercentage: 92,
    programs: ["Computer Science", "Electrical Engineering"]
  },
  {
    name: "Stanford University",
    country: "United States",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Stanford_Cardinal_logo.svg/1200px-Stanford_Cardinal_logo.svg.png",
    rank: 2,
    matchPercentage: 89,
    programs: ["Computer Science", "Data Science"]
  },
  {
    name: "University of Cambridge",
    country: "United Kingdom",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Cambridge_University_logo.svg/1200px-Cambridge_University_logo.svg.png",
    rank: 3,
    matchPercentage: 86,
    programs: ["Computer Science", "Mathematics"]
  },
  {
    name: "University of Oxford",
    country: "United Kingdom",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/1200px-Oxford-University-Circlet.svg.png",
    rank: 4,
    matchPercentage: 84,
    programs: ["Computer Science", "Engineering Science"]
  },
  {
    name: "ETH Zurich",
    country: "European Union",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/ETH_Z%C3%BCrich_Logo.svg/1200px-ETH_Z%C3%BCrich_Logo.svg.png",
    rank: 5,
    matchPercentage: 81,
    programs: ["Computer Science", "Electrical Engineering"]
  },
  {
    name: "University of Toronto",
    country: "Canada",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/University_of_Toronto_logo.svg/1200px-University_of_Toronto_logo.svg.png",
    rank: 6,
    matchPercentage: 79,
    programs: ["Computer Science", "Artificial Intelligence"]
  },
  {
    name: "University of Melbourne",
    country: "Australia & New Zealand",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/10/University_of_Melbourne_logo.svg/1200px-University_of_Melbourne_logo.svg.png",
    rank: 7,
    matchPercentage: 77,
    programs: ["Computer Science", "Information Technology"]
  },
  {
    name: "National University of Singapore",
    country: "Other",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/National_University_of_Singapore_logo.svg/1200px-National_University_of_Singapore_logo.svg.png",
    rank: 8,
    matchPercentage: 75,
    programs: ["Computer Science", "Information Systems"]
  },
  {
    name: "Technical University of Munich",
    country: "European Union",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Logo_of_the_Technical_University_of_Munich.svg/1200px-Logo_of_the_Technical_University_of_Munich.svg.png",
    rank: 9,
    matchPercentage: 72,
    programs: ["Computer Science", "Robotics"]
  },
  {
    name: "University of British Columbia",
    country: "Canada",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_University_of_British_Columbia_Logo.svg/1200px-The_University_of_British_Columbia_Logo.svg.png",
    rank: 10,
    matchPercentage: 70,
    programs: ["Computer Science", "Data Science"]
  }
];
